---
# tasks file for ipmitool
#
- name: install ipmitool
  package: name=ipmitool state=latest

- name: load kernel module
  modprobe: name={{ item }} state=present
  with_items:
    - ipmi_si
    - ipmi_devintf

- name: import secret variable file
  include_vars: "vault.yml"
  no_log: true

#- debug: msg={{ ipmitool_ansible_password }}
# - debug: msg={{ ipmitool_users }}

# Users
- name: Create user settings ipmi
  shell: sleep 1 && ipmitool user set name {{ item.value.id }} {{ item.key }}
  with_dict: "{{ ipmitool_users }}"

- name: Update password user settings ipmi
  shell: sleep 1 && ipmitool user set password {{ item.value.id }} {{ item.value.password }}
  with_dict: "{{ ipmitool_users }}"

- name: Enable IPMI user
  shell: sleep 1 && ipmitool user {% if item.value.enabled %}enable{% else %}disable{% endif %} {{ item.value.id }}
  when: item.key != "ADMIN"
  with_dict: "{{ ipmitool_users }}"

- name: Channel setaccess ipmi
  shell: |
    sleep 1 && ipmitool channel setaccess 1 {{ item.value.id }} \
    callin={% if item.value.enabled %}on{% else %}off{% endif %} \
    ipmi={% if item.value.enabled %}on{% else %}off{% endif %} \
    link={% if item.value.enabled %}on{% else %}off{% endif %} \
    privilege={% if item.value.enabled %}4{% else %}15{% endif %}
  with_dict: "{{ ipmitool_users }}"
